spring.application.name=E_Commerce_APP-1


# Database Configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/adityadb
#spring.datasource.username=root
#spring.datasource.password=141975
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ==========================================
# LIVE AIVEN DATABASE CONNECTION
# ==========================================
# Database - Render ke Env Vars se aayega
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
# JWT 
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
# (1 hour in ms)




# Google OAuth Config
google.client-id=${GOOGLE_CLIENT_ID}


# ===============================
# REDIS CONFIGURATION (OTP Storage)
# ===============================
#redis is not compatible with render so at a time we ignore 

#spring.data.redis.host=localhost
#spring.data.redis.port=6379
# Agar Redis par password nahi lagaya to ise blank chhod do
#spring.data.redis.password=

# ===============================
# EMAIL CONFIGURATION (Gmail SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=singhaadipratap1122@gmail.com
# Dhyan rahe: Ye normal password nahi, Google Account ka "App Password" hona chahiye
spring.mail.password=${MAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true





# ===============================
# TWILIO CONFIGURATION (SMS)
# ===============================
twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
twilio.phone-number=+17627753143


# Cloudinary Configuration
cloudinary.cloud-name=djyombzlq
cloudinary.api-key=673217435361853
cloudinary.api-secret=${CLOUDINARY_API_SECRET}


# Razorpay Configuration (TEST MODE)
 
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}


# Webhook Secret (Jo tumne Dashboard me likha tha)
razorpay.webhook.secret=${RAZORPAY_WEBHOOK_SECRET}
